apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
apiEndpoint:
  advertiseAddress: "0.0.0.0"
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: "${node_ip}"
    node-labels: "${node_labels}"
    register-with-taints: "${node_taints}"
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: "${kubernetes_version}"
controlPlaneEndpoint: "${node_ip}:6443"
schedulerExtraArgs:
  address: "${node_ip}"
etcd:
  external:
    endpoints: ${etcd_endpoints}
networking:
  dnsDomain: "${cluster_domain}"
  podSubnet: "${overlay_cidr}"
  serviceSubnet: "${service_cidr}"
apiServerCertSANs: ${cert_sans}
controllerManagerExtraArgs:
  allocate-node-cidrs: "true"
  cluster-cidr: "${overlay_cidr}"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs