apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
apiEndpoint:
  advertiseAddress: "${node_ip}"
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: "${node_ip}"
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: "stable-${join(".", slice(split(".", kubernetes_version), 0, 2))}"
controlPlaneEndpoint: "${node_ip}:6443"
schedulerExtraArgs:
  address: "${node_ip}"
etcd:
  external:
    endpoints:
      ${etcd_endpoints}
networking:
  dnsDomain: "${cluster_domain}"
  podSubnet: "${overlay_cidr}"
  serviceSubnet: "${service_cidr}"
apiServerCertSANs:
  ${cert_sans}
apiServerExtraArgs:
  endpoint-reconciler-type: lease